### ISSUE TITLE
Fix share screen and result page buttons

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#109]
These screens still show "Click "Next"" instead of "Tap "Continue"".  
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/cc852a15-9ff7-44e1-8a68-c756e6a37c2c)
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/40233f6b-f9e9-4341-ba8b-89b92d730464)

I think we tried to fix this [here](https://github.com/mplp/docassemble-mlhframework/issues/77) but it doesn't seem to be working.

But I actually think it might be better if these buttons did NOT say "undo" since that might make it sound like you can undo your sharing, which you cannot. Maybe we just don't want a back button on these pages? Is that possible?  Will back button: False do anything?

In a perfect world, the back button label on this page might in fact say back, since there's nothing to undo.
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/161a9fff-8c70-4ec1-a5be-e24c0872ee60)

But it looks like the framework tried to set the back button label to something else and it's not having any effect.
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/cadaf394-ddc4-40ba-9905-63c3cea3cef1)

**Comment by normon66** [comment]
Regarding the "Thanks for Sharing" / "Your message is on its way" pages (see `al_share_results`): it looks like the reason that is not working is because mlh_visual.yml (where the change was coded) was never included into mlh_interview_framework.yml:
![image](https://github.com/mplp/docassemble-mlhframework/assets/32527754/1327aa0b-76b1-4ad5-9b1f-b341a9ea8f48)
Navigational buttons could be configured there and that file included into the framework.

**Comment by ekressmiller** [comment]
good catch @normon66 !

**Comment by normon66** [comment]
Caught my own bug, but at least it got caught!
