### ISSUE TITLE
Save answers landing page

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-mlhframework#32]
After savings answers during an interview, this screen is shown. The text says "next" but the button is Continue; these should match. 

Bonus points: if we can determine the user's device type, we can use "Tap" if it's a phone or "Click" if a computer.

![image](https://github.com/mplp/docassemble-mlhframework/assets/32527754/73f2df35-0b98-416b-8536-354ff40f130a)

**Comment by BryceStevenWilley** [comment]
This is harder than it looks for no good reason; it's upstream code in Assembly Line, I think it says "Next" because it's a feature that ILAO has used and tested heavily, and they use "Next" for their continue button. But I can't find a way to get the specific name of the continue button for the current screen at the moment. I'm consulting the docassemble slack to see if there are any solutions.

> Bonus points: if we can determine the user's device type, we can use "Tap" if it's a phone or "Click" if a computer.

This is a bit of a rabbit hole that we've traveled down before; docassemble has a [device()](https://docassemble.org/docs/functions.html#device) function that determines if an OS is a mobile, tablet or computer. It works pretty well, but we can't determine if someone is using a touch device to operate a desktop computer, or a bluetooth mouse with a tablet, etc, so it's never going to be completely accurate. In AssemblyLine, we've mostly landed on "Tap" as a agnostic term that most people should get (don't think it was specifically user tested though). I can override our working if we want, but probably won't merge that upstream without some more conversations.

**Comment by normon66** [comment]
Thanks for the details. Both of these items are pretty trivial, and I think it's highly unlikely that a user would get stuck on this page since it says "next" but there's no "next" button. Same with tap/click. Probably safe to close this.

**Comment by BryceStevenWilley** [comment]
Following up from the docassemble slack, Johnathan says that "I'm not sure it is feasible to have a Python function that is called during the rendering of one screen part that can determine how another screen part will render." So unfortunately, I don't think this is going to happen. I'll close this issue.

"Click" instead of "Tap" is possible, upstream issue is https://github.com/SuffolkLITLab/docassemble-AssemblyLine/issues/802. If AL thinks it's a good change, it'll happen in this project automatically
