### ISSUE TITLE
Should we adjust exit behavior?

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-mlhframework#49]
From an accessibility audit of some of Vermont's docassemble forms:

> Some `button` elements should really be links since their function is navigation; for example, “Go to
  legal aid website” ["Exit" in our case] if the user can’t continue the interview. We recommend changing all
  elements having a navigation purpose to links. 3-Moderate

Some more details about using links for navigation and buttons for form logic are in https://ashleemboyer.com/blog/should-i-use-a-button-or-a-link.

I had a branch where I turned all of exit buttons into links, but realized a small issue that the accessibility audit folks might not have realized; the "Exit" button also deletes people's answers from the server If we want to keep the behavior of deleting people's answers when they exit, we should change the `exit label` to make that clear, e.g. "Exit and delete answers so far", but otherwise we should change our exit buttons to links.

Any thoughts?

**Comment by BryceStevenWilley** [comment]
An additional issue on Assembly Line here: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/issues/797

**Comment by normon66** [comment]
In skimming [that article](https://ashleemboyer.com/blog/should-i-use-a-button-or-a-link), and as the auditors mentioned, links should be used instead of buttons when the purpose is just navigation. 

If our Exit link/button ONLY navigated to a different url, then making it a link makes sense according to the "standards." However, the argument can be made that our Exit link/button does more than just navigation since it also performs an action (i.e. deleting answers), so therefore it _should_ be a button. 

I feel like changing each Exit label to something like "Exit and delete answers so far" would just introduce confusion or hesitancy to users. "What if I want to save by answers but also exit?" Does that mean that we would need two Exit buttons - one that removed the user's answers and one that kept them? 

I think the vast majority of the times someone got to an Exit point would be because they didn't qualify to use the resource for whatever reason, so I don't see much point or use in saving disqualifying answers, anyway. 

Just some thoughts!

**Comment by ekressmiller** [comment]
I think the "Exit" button in our case is functioning mostly as a way to end the interview. Being transported back to MLH is kind of a side-effect. To me, that conceptually makes a button feel like a reasonable choice based on what I know at this point, whether or not it's deleting data. (But this is the first time I'm considering this distinction, so that's not a strong conclusion.)

In terms of whether it should tell people it's going to delete, I think I agree with @normon66 that if we're using it in the first few screen-out questions in an interview, it's probably not super important to warn people before deleting. However, it could create confusion if someone was logged in, and tries to return to an interview by logging in and going to the My Interviews page, and there's nothing there. We're likely going to provide instructions on MLH on that way of returning to an interview.

With those considerations, I think I lean toward changing the behavior so that Exit buttons in an interview generally do **not** delete answers. That seems more in line with what a user would expect, especially if they're logged in and we've told them the interview saves every time they hit Continue.  Can we do that while still retaining the "Exit and Delete . . ." option in the menu?  And would there be a downside to making that change?

If we do keep the delete behavior in the exit buttons, we would need to be especially careful about using an Exit button later in an interview, once people have spent time entering some of their information.  (I could be wrong but I think some of our LHI interviews do have later-in-the-interview kickouts.)

**Comment by BryceStevenWilley** [comment]
> I think the vast majority of the times someone got to an Exit point would be because they didn't qualify to use the resource for whatever reason, so I don't see much point or use in saving disqualifying answers

That's true, but I usually flip that logic when I think about it; we aren't saving any PII from that user, so there's no urgent requirement to delete those answers (they are automatically deleted after 90 days of not interacting with the session).

> With those considerations, I think I lean toward changing the behavior so that Exit buttons in an interview generally do not delete answers

If we do that, I think we should convert those buttons into links. Mostly just because links navigate, and buttons do something with the form. I'm not sure I understand how you're thinking of "a way to end the interview" that is distinct from deleting your answers or just closing the tab.

> Can we do that while still retaining the "Exit and Delete . . ." option in the menu?

I think so; the "Exit and Delete" option does actually bring you to an explainer screen, saying that "Your progress on this document will be completely erased", so mis-clicks won't be an issue, and it's actions are clearly explained to users too.

**Comment by ekressmiller** [comment]
(FYI, feel free to keep the discussion going here but I also added this to our meeting agenda.)

**Comment by ekressmiller** [comment]
Discussed again at 1/4/24 meeting, decided we will stop deleting answers in this situation and change to links.  Example here: https://github.com/mplp/docassemble-mlhframework/commit/eab5cc0da6751f0b58932652c5784f9895c35f85

**Comment by BryceStevenWilley** [comment]
All of the individual repos should have exit buttons removed now, either on the main branch or in a PR! Going to close this.
