### ISSUE TITLE
Remove organization from intro page

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-mlhframework#76]
Per 12/21/23 call with team, remove the organization from the intro question. It is already in the header, so there is no need to include it again.

https://docs.google.com/document/d/1m5Fd0qP425uvJq8m4Zkfm_Ki9lVXuwF5t4ISUreTvlk/edit#bookmark=id.eom6bx3hyteb

**Comment by normon66** [comment]
Already address by #22

**Comment by ekressmiller** [comment]
@normon66 --This was fixed in the framework as you noted, but the security deposit interview has its own version of this question, so I think it needs to be overwritten specifically in the security deposit interview in order to fix it in that interview. (https://github.com/mplp/docassemble-MichiganLetterToLandlordReRet/blob/f75ad12986a3374675696f8735e520707001bc98/docassemble/MichiganLetterToLandlordReRet/data/questions/michigan_letter_to_landlord_re__ret.yml#L122)
