### ISSUE TITLE
Sign up Sign in links styling

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#87]
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/b746718f-b8fb-4665-9a51-036df66a4435)
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/dd4ee82e-9b0b-4ebc-b58a-5e5e434b8812)

Sign up is slightly bigger and a slightly bluer color.  Also Sign in becomes a button when hovered over and Sign up does not (Sign up changes color slightly when hovered over). 

I think the pure white (Sign in) is better. I think the size of Sign up is better, or maybe we could go in-between. 

A few too many factors going on in the css for me to immediately understand the simplest way to standardize them, but they are clearly different classes:
![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/18185676-540c-4258-9df8-d32c145d5d3c)

Also note "list" which only has Sign up in it.  -Not sure if that's something we can fix.

**Comment by ekressmiller** [comment]
@BryceStevenWilley I'd be grateful if you could take a look at this.

**Comment by normon66** [comment]
My two cents - agreed that the size of Sign up looks better, but with the button effect and look of Sign in.

**Comment by BryceStevenWilley** [comment]
Agreed it's not good now. I do think it's an upstream issue; I'm making an PR to docassemble, and I'll see what Jonathan says about it. If not, I think we could change the font size so they look closer to the same size, but changing both to be buttons would be a bit more difficult (there are a lot of CSS attributes that make the button button like, and we can only easily tweak one or two of those). 

As for why it's not good, the "Sign up" link is actually the same element that gets put into the hamburger dropdown on mobile screens, and there's actually a similarly styled "Sign in" that just gets hidden on bigger screens there. So it's only on bigger screens that there's this discrepancy. It's present on vanilla docassemble as well (which is why I think it's worth a shot at fixing upstream), as seen below. The Sign-in is more clearly a primary button there: we should consider a different button color when on the nav bar, so the button isn't identical to it's background. 

![Screenshot from 2024-03-09 15-34-36](https://github.com/mplp/docassemble-mlhframework/assets/6252212/4a2a7736-7bf9-4f0f-8c22-51ec0363a20a)

**Comment by ekressmiller** [comment]
Thanks for taking a look and making the Docassemble PR Bryce! We'll see what Jonathan says.

**Comment by ekressmiller** [comment]
@BryceStevenWilley Do you have a sense how long we should wait to see if Jonathan acts on your PR?

**Comment by BryceStevenWilley** [comment]
He usually looks at PRs every few weeks. Since he hasn't done anything with it, I can implement that workaround I mentioned (changing font size) today.

**Comment by ekressmiller** [comment]
Thanks Bryce, I think that works for now!

**Comment by ekressmiller** [comment]
I updated the production server with the new version, but the font size of the Sign In button does not seem to have changed. @BryceStevenWilley do you have any thoughts about trouble shooting that?

![image](https://github.com/mplp/docassemble-mlhframework/assets/110936328/82f8fa3d-aac1-4ca8-987e-2d1c3d8657d3)

**Comment by BryceStevenWilley** [comment]
Sorry to take so long to get to this! It looks like the issue was that on the production (and development servers), the Sign-in button added some extra information to the URL, which I didn't realize. I changed it to be any URL that signs you in, tested it on dev, and made #99, which should fix it!

**Comment by ekressmiller** [comment]
That worked, thank you Bryce!
