### ISSUE TITLE
Create portfolio-wide cover sheet

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-mlhframework#88]
As with existing A2J/HotDocs tool, create a dynamic `ALDocument` cover page as part of the framework that can be included in any other tool

**Comment by BryceStevenWilley** [comment]
Not sure if I'm misremembering things, but I thought that the A2J/HotDocs tools had a cover sheet because those tools required the file names to be something that didn't match the actual output forms, and it seemed to mostly be a work around?  Looking at https://github.com/mplp/docassemble-mlhframework/commit/327206483f2fdb5ad89ae5b743b45750289fb2d0, I can see any information that needs to be it's own cover page, and couldn't be integrated into the full instructions, like in https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/blob/main/docassemble/MLHMotionRegardingChildSupport/data/templates/mrcs_next_steps.docx.

**Comment by ekressmiller** [comment]
We talked about this at our last meeting and I think we're heading in the direction of integrating the info that used to go on the coversheet at the beginning of our directions. I think Brett's hoping to come up with a template that we can pull in to the beginning of each set of instructions. 

(Bryce, just for context as this convo continues, we are also planning to default back to our plainer instructions format for now, rather than the admittedly nicer two column design, mostly for efficiency reasons.)

**Comment by normon66** [comment]
Another part of initially having the coversheet was that so if someone was printing off forms in a public place, the top form wouldn't be a _Petition for Dissolution of Divorce_ or something like that. 

As Emily said, I'm working a solution where a framework-level coversheet can easily be included _as part of_ the same downloaded file as the instructions.
